apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: backend 
  janus-idp.io/tekton: backend
  backstage.io/kubernetes-id: backend
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: backend
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  