apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backend-gitops
  description: This is GitOps manifest for backend   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: backend
    janus-idp.io/tekton: backend 
    backstage.io/kubernetes-id: backend 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:backend
