apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: backend
  janus-idp.io/tekton: backend
  backstage.io/kubernetes-id: backend
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: backend
resources: 
- deployment.yaml
- route.yaml
- service.yaml
